### PR TITLE
Make Lets Start link to FCC

### PR DESCRIPTION
**Pull request by SaintPeter**
Turn the "Let's Start" On the last page into a link to FCC.

Tested Locally.

### CODE REVIEW

**Comment by rxsharp** [comment]
GREAT IDEA!

**Comment by rxsharp** [comment]
This is a great touch to the presentation. I wish I had a link on the "LET'S START" slide earlier today during the presentation lol

**Comment by SaintPeter** [comment]
:smile: 
The value of Open Source, eh?

**Comment by rxsharp** [comment]
I love it. Thanks so much for all of your help. I've been getting acclimated into the sharing of code culture for the past couple months and it's so awesome. I'm happy to help and so happy to get help as well :)

**Pull request merged**
